site_name: Malte Hedderich
theme:
  name: material
  palette:
    scheme: slate
  favicon: images/favicon/favicon-192.png
  features:
    - header.autohide
plugins:
  - blog:
      blog_dir: .
      blog_toc: true
